export const VALIDATION_LIMITS = {
  TASK_TITLE_MAX: 200,
  TASK_DESCRIPTION_MAX: 5_000,
  PROJECT_NAME_MAX: 120,
  PROJECT_DESCRIPTION_MAX: 2_000,
  TENANT_NAME_MAX: 120,
  USER_NAME_MAX: 120,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 128,
  TASKS_PAGE_SIZE_MAX: 100,
  TASKS_PAGE_SIZE_DEFAULT: 20,
} as const;

export const RATE_LIMITS = {
  GLOBAL_PER_MINUTE: 120,
  LOGIN_PER_15_MIN: 10,
  REGISTER_PER_HOUR: 5,
  FORGOT_PASSWORD_PER_HOUR: 5,
  VERIFY_OTP_PER_15_MIN: 10,
  SOCKET_ROOM_JOIN_PER_MINUTE: 30,
} as const;

export const SESSION_TTL_SECONDS = {
  DEFAULT: 60 * 60 * 24 * 7,
  MAX: 60 * 60 * 24 * 30,
} as const;
